### ISSUE TITLE
[Bug]: Exception occurred: PytorchStreamReader failed reading file data/1037: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by yehonatan5f** [deforum-art/sd-webui-text2video#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

I moved the model files as needed to /models/ModelScope/t2v and it always shows me this error when I try to generate a video:

Traceback (most recent call last):
  File "G:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 94, in process
    process_modelscope(skip_video_creation, ffmpeg_location, ffmpeg_crf, ffmpeg_preset, fps, add_soundtrack, soundtrack_path, \
  File "G:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 152, in process_modelscope
    pipe = setup_pipeline()
  File "G:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 42, in setup_pipeline
    return TextToVideoSynthesis(ph.models_path+'/ModelScope/t2v')
  File "G:\Stable diffusion\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\t2v_pipeline.py", line 84, in __init__
    torch.load(
  File "G:\Stable diffusion\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "G:\Stable diffusion\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "G:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "G:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pickle.py", line 1254, in load_binpersid
    self.append(self.persistent_load(pid))
  File "G:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "G:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
RuntimeError: PytorchStreamReader failed reading file data/1037: invalid header or archive is corrupted
Exception occurred: PytorchStreamReader failed reading file data/1037: invalid header or archive is corrupted

I checked and the files were okay and not broken so I really don't know what's going on....

<img width="962" alt="image" src="https://user-images.githubusercontent.com/123481656/231162550-72542f15-a1fe-4b3c-a883-3dd1c3587b98.png">

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### WebUI and Deforum extension Commit IDs

webui commit id - 
txt2vid commit id -

### What GPU were you using for launching?

RTX 3070 had enough available VRAM

### Settings

--xformers --reinstall-xformers

### Console logs

```Shell
Traceback (most recent call last):
  File "G:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 94, in process
    process_modelscope(skip_video_creation, ffmpeg_location, ffmpeg_crf, ffmpeg_preset, fps, add_soundtrack, soundtrack_path, \
  File "G:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 152, in process_modelscope
    pipe = setup_pipeline()
  File "G:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-text2video\scripts\text2vid.py", line 42, in setup_pipeline
    return TextToVideoSynthesis(ph.models_path+'/ModelScope/t2v')
  File "G:\Stable diffusion\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\t2v_pipeline.py", line 84, in __init__
    torch.load(
  File "G:\Stable diffusion\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "G:\Stable diffusion\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "G:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "G:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pickle.py", line 1254, in load_binpersid
    self.append(self.persistent_load(pid))
  File "G:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "G:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1079, in load_tensor    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
RuntimeError: PytorchStreamReader failed reading file data/1037: invalid header or archive is corrupted
Exception occurred: PytorchStreamReader failed reading file data/1037: invalid header or archive is corrupted
```

**Comment by chimera15** [comment]
Same. 

File "L:\supersd2\stabdif3\extensions\sd-webui-text2video\scripts\text2vid.py", line 94, in process
    process_modelscope(skip_video_creation, ffmpeg_location, ffmpeg_crf, ffmpeg_preset, fps, add_soundtrack, soundtrack_path, \
  File "L:\supersd2\stabdif3\extensions\sd-webui-text2video\scripts\text2vid.py", line 152, in process_modelscope
    pipe = setup_pipeline()
  File "L:\supersd2\stabdif3\extensions\sd-webui-text2video\scripts\text2vid.py", line 42, in setup_pipeline
    return TextToVideoSynthesis(ph.models_path+'/ModelScope/t2v')
  File "L:\supersd2\stabdif3/extensions/sd-webui-text2video/scripts\modelscope\t2v_pipeline.py", line 59, in __init__
    config_dict = json.load(f)
  File "C:\Users\lrdce\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\lrdce\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lrdce\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lrdce\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Exception occurred: Expecting value: line 1 column 1 (char 0)
