### ISSUE TITLE
[Bug]: No tab after adding extension 

### ISSUE THREAD

**Issue by ibackstrom** [deforum-art/sd-webui-text2video#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

1. No tab appeared after adding to webui extension 

### Steps to reproduce the problem

1. Installed proper CUDA
2. Installed numexpr

### WebUI and Deforum extension Commit IDs

![Screenshot_65](https://user-images.githubusercontent.com/24996539/231884013-1a5f0a22-dc8e-48d4-b2e3-08bd66435298.png)

### What GPU were you using for launching?

2080Ti 

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

![Screenshot_65](https://user-images.githubusercontent.com/24996539/231883937-013816eb-7f1a-4fed-91ea-e6e902258e41.png)

### Console logs

```Shell
Error loading script: key_frames.py
Traceback (most recent call last):
  File "C:\Users\lapla\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lapla\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lapla\stable-diffusion-webui\scripts\key_frames.py", line 3, in <module>
    import numexpr
ModuleNotFoundError: No module named 'numexpr'

Error loading script: text2vid.py
Traceback (most recent call last):
  File "C:\Users\lapla\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lapla\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lapla\stable-diffusion-webui\scripts\text2vid.py", line 2, in <module>
    from scripts.key_frames import T2VAnimKeys #TODO: move to deforum_tools
  File "C:\Users\lapla\stable-diffusion-webui\scripts\key_frames.py", line 3, in <module>
    import numexpr
ModuleNotFoundError: No module named 'numexpr'
```

**Comment by kabachuha** [comment]
Oops, forgot that `numexpr` is not being preinstalled along with the webui

**Comment by helloansuman** [comment]
Any solution?
