### ISSUE TITLE
[Bug]: Not working at all on Apple silicon

### ISSUE THREAD

**Issue by elchupacabrinski** [deforum-art/sd-webui-text2video#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

**When trying to render anything with the ModelScope Model I get this error:**

Traceback (most recent call last):
File "/Users/konsti/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/t2v_helpers/render.py", line 24, in run
vids_pack = process_modelscope(args_dict)
File "/Users/konsti/stable-diffusion-webui/extensions/sd-webui-text2video/scripts/modelscope/process_modelscope.py", line 45, in process_modelscope
del shared.sd_model
AttributeError: can't delete attribute 'sd_model'
Exception occurred: can't delete attribute 'sd_model'

**And with the VideoCrafter one I get this:**
AssertionError: Torch not compiled with CUDA enabled
Exception occurred: Torch not compiled with CUDA enabled

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### WebUI and Deforum extension Commit IDs

webui commit id - Newest of Vlad and Auto1111
txt2vid commit id - 2a7b60d6

### Torch version

2.0.0

### What GPU were you using for launching?

None

### On which platform are you launching the webui backend with the extension?

Local PC setup (Mac)

### Settings

Default

### Console logs

```Shell
(base) XXXX@XXXXs-MBP automatic % ./webui.sh --reinstall
Create and activate python venv
Launching launch.py...
12:39:20-185504 INFO     Starting SD.Next                                                                               
12:39:20-187343 INFO     Python 3.10.9 on Darwin                                                                        
12:39:20-202768 INFO     Version: f6f1a73b Wed May 17 06:15:18 2023 -0400                                               
12:39:20-323374 INFO     Setting environment tuning                                                                     
12:39:20-323941 INFO     Forcing reinstall of all packages                                                              
12:39:20-324841 INFO     Installing package: torch==2.0.0 torchvision==0.15.1                                           
12:39:21-857822 INFO     Torch 2.0.0                                                                                    
12:39:21-858563 INFO     Installing package: tensorflow==2.12.0                                                         
12:39:22-195912 INFO     Verifying requirements                                                                         
12:39:22-197071 INFO     Installing package: addict                                                                     
12:39:23-100249 INFO     Installing package: aenum                                                                      
12:39:23-994047 INFO     Installing package: aiohttp                                                                    
12:39:25-014507 INFO     Installing package: anyio                                                                      
12:39:25-941717 INFO     Installing package: appdirs                                                                    
12:39:26-855973 INFO     Installing package: astunparse                                                                 
12:39:27-770397 INFO     Installing package: bitsandbytes                                                               
12:39:28-681701 INFO     Installing package: blendmodes                                                                 
12:39:29-639536 INFO     Installing package: clean-fid                                                                  
12:39:30-557545 INFO     Installing package: easydev                                                                    
12:39:31-473965 INFO     Installing package: extcolors                                                                  
12:39:32-365196 INFO     Installing package: facexlib                                                                   
12:39:33-296334 INFO     Installing package: filetype                                                                   
12:39:34-195216 INFO     Installing package: font-roboto                                                                
12:39:35-073429 INFO     Installing package: fonts                                                                      
12:39:35-977190 INFO     Installing package: future                                                                     
12:39:36-878286 INFO     Installing package: gdown                                                                      
12:39:37-804609 INFO     Installing package: gfpgan                                                                     
12:39:38-822657 INFO     Installing package: GitPython                                                                  
12:39:39-748540 INFO     Installing package: httpcore                                                                   
12:39:40-653947 INFO     Installing package: inflection                                                                 
12:39:41-543279 INFO     Installing package: jsonmerge                                                                  
12:39:42-450014 INFO     Installing package: kornia                                                                     
12:39:43-358086 INFO     Installing package: lark                                                                       
12:39:44-258170 INFO     Installing package: lmdb                                                                       
12:39:45-168913 INFO     Installing package: lpips                                                                      
12:39:46-074486 INFO     Installing package: numpy                                                                      
12:39:47-073987 INFO     Installing package: omegaconf                                                                  
12:39:48-019966 INFO     Installing package: open-clip-torch                                                            
12:39:48-949985 INFO     Installing package: opencv-contrib-python                                                      
12:39:49-919490 INFO     Installing package: piexif                                                                     
12:39:50-839734 INFO     Installing package: Pillow                                                                     
12:39:51-838546 INFO     Installing package: psutil                                                                     
12:39:52-768731 INFO     Installing package: pyyaml                                                                     
12:39:53-669621 INFO     Installing package: realesrgan                                                                 
12:39:54-675084 INFO     Installing package: resize-right                                                               
12:39:55-570182 INFO     Installing package: rich                                                                       
12:39:56-485538 INFO     Installing package: safetensors                                                                
12:39:57-416522 INFO     Installing package: scipy                                                                      
12:39:58-367978 INFO     Installing package: tb_nightly                                                                 
12:39:59-506784 INFO     Installing package: toml                                                                       
12:40:00-401253 INFO     Installing package: torchdiffeq                                                                
12:40:01-293202 INFO     Installing package: torchsde                                                                   
12:40:02-185701 INFO     Installing package: voluptuous                                                                 
12:40:03-068827 INFO     Installing package: yapf                                                                       
12:40:03-975536 INFO     Installing package: scikit-image                                                               
12:40:04-905270 INFO     Installing package: basicsr                                                                    
12:40:05-897834 INFO     Installing package: requests==2.30.0                                                           
12:40:06-845768 INFO     Installing package: tqdm==4.65.0                                                               
12:40:07-781140 INFO     Installing package: accelerate==0.18.0                                                         
12:40:08-694814 INFO     Installing package: opencv-python==4.7.0.72                                                    
12:40:09-658253 INFO     Installing package: diffusers==0.16.1                                                          
12:40:10-590072 INFO     Installing package: einops==0.4.1                                                              
12:40:11-541876 INFO     Installing package: gradio==3.29.0                                                             
12:40:12-687455 INFO     Installing package: numexpr==2.8.4                                                             
12:40:13-643542 INFO     Installing package: pandas==1.5.3                                                              
12:40:14-656434 INFO     Installing package: protobuf==3.20.3                                                           
12:40:15-686358 INFO     Installing package: pytorch_lightning==1.9.4                                                   
12:40:16-680032 INFO     Installing package: transformers==4.26.1                                                       
12:40:17-609778 INFO     Installing package: timm==0.6.13                                                               
12:40:18-570611 INFO     Installing package: tomesd==0.1.2                                                              
12:40:19-524400 INFO     Installing package: urllib3==1.26.15                                                           
12:40:20-495843 INFO     Installing package: onnxruntime==1.14.0                                                        
12:40:20-813323 ERROR    Error running pip: install --upgrade onnxruntime==1.14.0                                       
12:40:20-814469 INFO     Installing packages                                                                            
12:40:20-814814 INFO     Installing package:                                                                            
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1                
12:40:25-006425 INFO     Running setup                                                                                  
12:40:25-007465 INFO     Installing repositories                                                                        
12:40:25-048499 INFO     Installing submodules                                                                          
12:40:25-427292 INFO     Updating submodules                                                                            
12:40:36-678618 INFO     Extensions enabled: ['SwinIR', 'clip-interrogator-ext', 'sd-dynamic-thresholding',             
                         'prompt-bracket-checker', 'sd-webui-controlnet', 'ScuNET', 'stable-diffusion-webui-rembg',     
                         'sd-webui-model-converter', 'Lora', 'sd-extension-system-info',                                
                         'stable-diffusion-webui-images-browser', 'LDSR', 'multidiffusion-upscaler-for-automatic1111',  
                         'a1111-sd-webui-lycoris']                                                                      
12:40:36-679740 INFO     Updating Wiki                                                                                  
12:40:37-165190 WARNING  Setup complete with errors: 1                                                                  
12:40:37-166111 WARNING  See log file for more details: setup.log                                                       
12:40:37-166646 INFO     Running extension preloading                                                                   
12:40:37-168210 INFO     Server arguments: ['--reinstall']                                                              
No module 'xformers'. Proceeding without it.
12:40:39-016188 INFO     Libraries loaded                                                                               
12:40:39-121088 INFO     Available models: /Users/XXXX/automatic/models/Stable-diffusion 26                           
ControlNet v1.1.173
ControlNet v1.1.173
Image Browser: ImageReward is not installed, cannot be used.
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
12:40:40-128752 INFO     Loading UI theme: black-orange                                                                 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
12:40:40-979506 INFO     Local URL: http://127.0.0.1:7860/                                                              
12:40:40-980239 INFO     API Docs: http://127.0.0.1:7860/docs                                                           
12:40:40-980585 INFO     Initializing middleware                                                                        
12:40:41-271976 INFO     CUDA FP16 test passed but desired mode is set to FP32                                          
12:40:41-272646 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32             
Loading weights: /Users/XXXX/automatic/models/Stable-diffusion/2.1-Based/Artius/artiusV21_v21.safetensors ━━━ 0.… -:-…
                                                                                                                GB      
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
12:40:41-573469 INFO     Model created from config:                                                                     
                         /Users/XXXX/automatic/models/Stable-diffusion/2.1-Based/Artius/artiusV21_v21.yaml            
12:40:42-803333 INFO     Applying scaled dot product cross attention optimization                                       
12:40:42-816964 INFO     Embeddings loaded: 17 ['DrD_PNTE768', 'KittyPic', 'XXXX-Embedding-2000',                     
                         'XXXX-Embedding-2500', 'XXXX-Embedding-3000', 'XXXX-Embedding-3500',                     
                         'XXXX-Embedding-4000', 'XXXX-Embedding-4500', 'XXXX-Embedding-5000',                     
                         'XXXX-Embedding-5500', 'XXXX-Embedding-6000', 'XXXX-Embedding-6500',                     
                         'XXXX-Embedding-7000', 'XXXX-Embedding-7500', 'XXXX-Embedding-8000',                     
                         'XXXX-Embedding-8500', 'XXXX-Embedding-9000']                                              
12:40:42-817891 INFO     Textual inversion embeddings skipped(1): RFKTR_bontrex-150                                     
12:40:42-821637 INFO     Model loaded in 1.6s (load=0.2s create=0.1s apply=0.4s vae=0.3s move=0.5s)                     
12:40:42-937565 INFO     Model load finished: {'ram': {'used': 5.14, 'total': 64.0}}                                    
12:40:43-060026 INFO     Startup time: 5.9s (torch=0.6s gradio=0.9s libraries=0.4s models=0.1s scripts=0.9s opts        
                         onchange=0.1s ui=0.8s start=0.1s scripts app_started_callback=0.2s checkpoint=1.9s)            
12:40:43-061079 INFO     Memory used: 2.71 total: 64.0                                                                  
Progress 2.67it/s ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:07
12:52:48-705351 INFO     Extension install: https://github.com/deforum-art/sd-webui-text2video.git                      
12:52:48-706924 INFO     Installing extension: https://github.com/deforum-art/sd-webui-text2video.git into              
                         /Users/XXXX/automatic/extensions/sd-webui-text2video                                         
^C12:53:02-222073 INFO     Exiting                                                                                        
(base) XXXX@XXXXs-MBP automatic % 
(base) XXXX@XXXXs-MBP automatic % 
(base) XXXX@XXXXs-MBP automatic % 
(base) XXXX@XXXXs-MBP automatic % ./webui.sh --reinstall
Create and activate python venv
Launching launch.py...
12:53:04-449220 INFO     Starting SD.Next                                                                               
12:53:04-451156 INFO     Python 3.10.9 on Darwin                                                                        
12:53:04-468476 INFO     Version: f6f1a73b Wed May 17 06:15:18 2023 -0400                                               
12:53:04-749875 INFO     Setting environment tuning                                                                     
12:53:04-752418 INFO     Forcing reinstall of all packages                                                              
12:53:04-754338 INFO     Installing package: torch==2.0.0 torchvision==0.15.1                                           
12:53:06-191356 INFO     Torch 2.0.0                                                                                    
12:53:06-191949 INFO     Installing package: tensorflow==2.12.0                                                         
12:53:06-507584 INFO     Verifying requirements                                                                         
12:53:06-508616 INFO     Installing package: addict                                                                     
12:53:07-377685 INFO     Installing package: aenum                                                                      
12:53:08-246553 INFO     Installing package: aiohttp                                                                    
12:53:09-248412 INFO     Installing package: anyio                                                                      
12:53:10-141952 INFO     Installing package: appdirs                                                                    
12:53:11-008352 INFO     Installing package: astunparse                                                                 
12:53:11-919323 INFO     Installing package: bitsandbytes                                                               
12:53:12-786659 INFO     Installing package: blendmodes                                                                 
12:53:13-686273 INFO     Installing package: clean-fid                                                                  
12:53:14-638800 INFO     Installing package: easydev                                                                    
12:53:15-502344 INFO     Installing package: extcolors                                                                  
12:53:16-513044 INFO     Installing package: facexlib                                                                   
12:53:17-437827 INFO     Installing package: filetype                                                                   
12:53:18-359715 INFO     Installing package: font-roboto                                                                
12:53:19-317207 INFO     Installing package: fonts                                                                      
12:53:20-305564 INFO     Installing package: future                                                                     
12:53:21-256779 INFO     Installing package: gdown                                                                      
12:53:22-212188 INFO     Installing package: gfpgan                                                                     
12:53:23-530162 INFO     Installing package: GitPython                                                                  
12:53:24-456717 INFO     Installing package: httpcore                                                                   
12:53:25-403444 INFO     Installing package: inflection                                                                 
12:53:26-316645 INFO     Installing package: jsonmerge                                                                  
12:53:27-240454 INFO     Installing package: kornia                                                                     
12:53:28-144962 INFO     Installing package: lark                                                                       
12:53:29-042952 INFO     Installing package: lmdb                                                                       
12:53:30-047543 INFO     Installing package: lpips                                                                      
12:53:31-019472 INFO     Installing package: numpy                                                                      
12:53:32-095276 INFO     Installing package: omegaconf                                                                  
12:53:33-054192 INFO     Installing package: open-clip-torch                                                            
12:53:34-112277 INFO     Installing package: opencv-contrib-python                                                      
12:53:35-103674 INFO     Installing package: piexif                                                                     
12:53:36-024377 INFO     Installing package: Pillow                                                                     
12:53:37-034706 INFO     Installing package: psutil                                                                     
12:53:37-976073 INFO     Installing package: pyyaml                                                                     
12:53:38-886677 INFO     Installing package: realesrgan                                                                 
12:53:39-883528 INFO     Installing package: resize-right                                                               
12:53:40-766812 INFO     Installing package: rich                                                                       
12:53:41-663009 INFO     Installing package: safetensors                                                                
12:53:42-553817 INFO     Installing package: scipy                                                                      
12:53:43-505396 INFO     Installing package: tb_nightly                                                                 
12:53:44-614549 INFO     Installing package: toml                                                                       
12:53:45-498309 INFO     Installing package: torchdiffeq                                                                
12:53:46-394764 INFO     Installing package: torchsde                                                                   
12:53:47-281672 INFO     Installing package: voluptuous                                                                 
12:53:48-152699 INFO     Installing package: yapf                                                                       
12:53:49-052852 INFO     Installing package: scikit-image                                                               
12:53:49-977595 INFO     Installing package: basicsr                                                                    
12:53:50-931572 INFO     Installing package: requests==2.30.0                                                           
12:53:51-858669 INFO     Installing package: tqdm==4.65.0                                                               
12:53:52-771686 INFO     Installing package: accelerate==0.18.0                                                         
12:53:53-668161 INFO     Installing package: opencv-python==4.7.0.72                                                    
12:53:54-605164 INFO     Installing package: diffusers==0.16.1                                                          
12:53:55-500291 INFO     Installing package: einops==0.4.1                                                              
12:53:56-396814 INFO     Installing package: gradio==3.29.0                                                             
12:53:57-423657 INFO     Installing package: numexpr==2.8.4                                                             
12:53:58-325016 INFO     Installing package: pandas==1.5.3                                                              
12:53:59-301579 INFO     Installing package: protobuf==3.20.3                                                           
12:54:00-312280 INFO     Installing package: pytorch_lightning==1.9.4                                                   
12:54:01-315234 INFO     Installing package: transformers==4.26.1                                                       
12:54:02-258341 INFO     Installing package: timm==0.6.13                                                               
12:54:03-163333 INFO     Installing package: tomesd==0.1.2                                                              
12:54:04-178592 INFO     Installing package: urllib3==1.26.15                                                           
12:54:05-100358 INFO     Installing package: onnxruntime==1.14.0                                                        
12:54:05-404617 ERROR    Error running pip: install --upgrade onnxruntime==1.14.0                                       
12:54:05-405805 INFO     Installing packages                                                                            
12:54:05-406173 INFO     Installing package:                                                                            
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1                
12:54:08-851905 INFO     Running setup                                                                                  
12:54:08-852902 INFO     Installing repositories                                                                        
12:54:08-896559 INFO     Installing submodules                                                                          
12:54:09-282876 INFO     Updating submodules                                                                            
12:54:33-603454 INFO     Extensions enabled: ['SwinIR', 'clip-interrogator-ext', 'sd-dynamic-thresholding',             
                         'prompt-bracket-checker', 'sd-webui-controlnet', 'ScuNET', 'stable-diffusion-webui-rembg',     
                         'sd-webui-model-converter', 'Lora', 'sd-extension-system-info',                                
                         'stable-diffusion-webui-images-browser', 'LDSR', 'multidiffusion-upscaler-for-automatic1111',  
                         'a1111-sd-webui-lycoris', 'sd-webui-text2video']                                               
12:54:33-604843 INFO     Updating Wiki                                                                                  
12:54:34-081012 WARNING  Setup complete with errors: 1                                                                  
12:54:34-082477 WARNING  See log file for more details: setup.log                                                       
12:54:34-083368 INFO     Running extension preloading                                                                   
12:54:34-085714 INFO     Server arguments: ['--reinstall']                                                              
No module 'xformers'. Proceeding without it.
12:54:35-932570 INFO     Libraries loaded                                                                               
12:54:36-033919 INFO     Available models: /Users/XXXX/automatic/models/Stable-diffusion 26                           
ControlNet v1.1.173
ControlNet v1.1.173
Image Browser: ImageReward is not installed, cannot be used.
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
12:54:36-935629 INFO     Libraries loaded                                                                               
12:54:37-050755 INFO     Loading UI theme: black-orange                                                                 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
12:54:37-898947 INFO     Local URL: http://127.0.0.1:7860/                                                              
12:54:37-899586 INFO     API Docs: http://127.0.0.1:7860/docs                                                           
12:54:37-899916 INFO     Initializing middleware                                                                        
12:54:38-173929 INFO     CUDA FP16 test passed but desired mode is set to FP32                                          
12:54:38-174556 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32             
Loading weights: /Users/XXXX/automatic/models/Stable-diffusion/2.1-Based/Artius/artiusV21_v21.safetensors ━━━ 0.… -:-…
                                                                                                                GB      
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
12:54:38-457877 INFO     Model created from config:                                                                     
                         /Users/XXXX/automatic/models/Stable-diffusion/2.1-Based/Artius/artiusV21_v21.yaml            
12:54:39-676854 INFO     Applying scaled dot product cross attention optimization                                       
12:54:39-692781 INFO     Embeddings loaded: 17 ['DrD_PNTE768', 'KittyPic', 'XXXX-Embedding-2000',                     
                         'XXXX-Embedding-2500', 'XXXX-Embedding-3000', 'XXXX-Embedding-3500',                     
                         'XXXX-Embedding-4000', 'XXXX-Embedding-4500', 'XXXX-Embedding-5000',                     
                         'XXXX-Embedding-5500', 'XXXX-Embedding-6000', 'XXXX-Embedding-6500',                     
                         'XXXX-Embedding-7000', 'XXXX-Embedding-7500', 'XXXX-Embedding-8000',                     
                         'XXXX-Embedding-8500', 'XXXX-Embedding-9000']                                              
12:54:39-693593 INFO     Textual inversion embeddings skipped(1): RFKTR_bontrex-150                                     
12:54:39-696862 INFO     Model loaded in 1.5s (load=0.2s create=0.1s apply=0.4s vae=0.3s move=0.5s)                     
12:54:39-813643 INFO     Model load finished: {'ram': {'used': 5.17, 'total': 64.0}}                                    
12:54:39-934451 INFO     Startup time: 5.8s (torch=0.6s gradio=0.9s libraries=0.4s models=0.1s scripts=0.9s opts        
                         onchange=0.1s ui=0.8s start=0.1s scripts app_started_callback=0.2s checkpoint=1.9s)            
12:54:39-935514 INFO     Memory used: 2.74 total: 64.0                                                                  
text2video — The model selected is:  ModelScope
 text2video extension for auto1111 webui
Git commit: <p>2a7b60d6</p><p>Sun May14 2023 18:36</p>
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
device mps
Working in txt2vid mode
Traceback (most recent call last):
  File "/Users/XXXX/automatic/extensions/sd-webui-text2video/scripts/t2v_helpers/render.py", line 24, in run
    vids_pack = process_modelscope(args_dict)
  File "/Users/XXXX/automatic/extensions/sd-webui-text2video/scripts/modelscope/process_modelscope.py", line 136, in process_modelscope
    pbar = tqdm(range(args.batch_count), leave=False)
  File "/Users/XXXX/automatic/venv/lib/python3.10/site-packages/tqdm/_tqdm.py", line 383, in __new__
  File "/Users/XXXX/automatic/venv/lib/python3.10/site-packages/tqdm/_tqdm.py", line 68, in __init__
AttributeError: module 'sys' has no attribute 'setcheckinterval'
Exception occurred: module 'sys' has no attribute 'setcheckinterval'
Exception ignored in: <function tqdm.__del__ at 0x1076667a0>
Traceback (most recent call last):
  File "/Users/XXXX/automatic/venv/lib/python3.10/site-packages/tqdm/_tqdm.py", line 764, in __del__
  File "/Users/XXXX/automatic/venv/lib/python3.10/site-packages/tqdm/_tqdm.py", line 994, in close
AttributeError: 'tqdm' object has no attribute 'disable'
text2video — The model selected is:  VideoCrafter (WIP)
 text2video extension for auto1111 webui
Git commit: <p>2a7b60d6</p><p>Sun May14 2023 18:36</p>
VideoCrafter config: 
 {'model': {'target': 'lvdm.models.ddpm3d.LatentDiffusion', 'params': {'linear_start': 0.00085, 'linear_end': 0.012, 'num_timesteps_cond': 1, 'log_every_t': 200, 'timesteps': 1000, 'first_stage_key': 'video', 'cond_stage_key': 'caption', 'image_size': [32, 32], 'video_length': 16, 'channels': 4, 'cond_stage_trainable': False, 'conditioning_key': 'crossattn', 'scale_by_std': False, 'scale_factor': 0.18215, 'unet_config': {'target': 'lvdm.models.modules.openaimodel3d.UNetModel', 'params': {'image_size': 32, 'in_channels': 4, 'out_channels': 4, 'model_channels': 320, 'attention_resolutions': [4, 2, 1], 'num_res_blocks': 2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8, 'transformer_depth': 1, 'context_dim': 768, 'use_checkpoint': True, 'legacy': False, 'kernel_size_t': 1, 'padding_t': 0, 'temporal_length': 16, 'use_relative_position': True}}, 'first_stage_config': {'target': 'lvdm.models.autoencoder.AutoencoderKL', 'params': {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig': {'double_z': True, 'z_channels': 4, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'cond_stage_config': {'target': 'lvdm.models.modules.condition_modules.FrozenCLIPEmbedder'}}}}
Loading model from /Users/XXXX/automatic/models/VideoCrafter/model.ckpt
LatentDiffusion: Running in eps-prediction mode
Successfully initialize the diffusion model !
DiffusionWrapper has 958.92 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "/Users/XXXX/automatic/extensions/sd-webui-text2video/scripts/t2v_helpers/render.py", line 26, in run
    vids_pack = process_videocrafter(args_dict)
  File "/Users/XXXX/automatic/extensions/sd-webui-text2video/scripts/videocrafter/process_videocrafter.py", line 41, in process_videocrafter
    model, _, _ = load_model(config, ph.models_path+'/VideoCrafter/model.ckpt', #TODO: support safetensors and stuff
  File "/Users/XXXX/automatic/extensions/sd-webui-text2video/scripts/videocrafter/sample_utils.py", line 37, in load_model
    model.cuda()
  File "/Users/XXXX/automatic/venv/lib/python3.10/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 69, in cuda
    device = torch.device("cuda", torch.cuda.current_device())
  File "/Users/XXXX/automatic/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/Users/XXXX/automatic/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Exception occurred: Torch not compiled with CUDA enabled
```

**Comment by elchupacabrinski** [comment]
format is not incorrect smh bot
