### ISSUE TITLE
[Bug]: A1111 doenst launch after installation of this extension

### ISSUE THREAD

**Issue by EternalValkorion** [deforum-art/sd-webui-text2video#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

After installation of the extension in A1111 i clicked "Apply and restart UI". A1111 gives me this Error while startup and wont start

My PC setup:
CPU: Intel Xeon W-2145
RAM: 16GB DDR4
GPU: NVIDIA Quadro RTX 5000
OS: Windows 10

### Steps to reproduce the problem

Start A1111 after installing this extension

### What should have happened?

A1111 starts and displays the WEBUI.

### WebUI and Deforum extension Commit IDs

WEBUI Commihash - cf2772fab0af5573da775e7437e6acdca424f26e
Launcher Version 1.7.0

### Torch version

Cant see will add later

### What GPU were you using for launching?

RTX 5000 - 16GB VRAM

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

Starting Arguments are now: --xformers --ckpt-dir 'C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion'

### Console logs

```Shell
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   Found a custom WebUI Config
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.9150.1013 found in registry:  C:\Users\Falko\AppData\Local\Programs\Python\Python310\
 !   This is not the recommended version of Python and will probably cause errors
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  C:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers --ckpt-dir 'C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Webui
 ✓   Done
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: a1111-sd-webui-lycoris
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-additional-networks
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-animatediff
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-controlnet
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd-webui-text2video
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: stable-diffusion-webui-images-browser
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: StylePile
 ✓   Done
 i   Arguments are now: --xformers --ckpt-dir 'C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --autolaunch --xformers --ckpt-dir C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion
Traceback (most recent call last):
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 44, in main
    start()
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\launch_utils.py", line 460, in start
    import webui
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\gradio_client\client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\__init__.py", line 370, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\Falko\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Falko\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\hf_api.py", line 48, in <module>
    from tqdm.auto import tqdm as base_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
Drücken Sie eine beliebige Taste . . .
```

**Comment by enochianborg** [comment]
https://github.com/CiaraStrawberry/TemporalKit/issues/81 This thread solved this issue for several others and my instance.  This does not solve other problems which are keeping text2video from showing in tab or loading.  There seems to be some interaction issues with Automatic1111.  I hope they are solved soon so I can actually run this extention.

**Comment by nitinmukesh** [comment]
I checked and it seems to be working fine.
https://www.youtube.com/watch?v=6gbadk8lXus

**Comment by nitinmukesh** [comment]
> [CiaraStrawberry/TemporalKit#81](https://github.com/CiaraStrawberry/TemporalKit/issues/81) This thread solved this issue for several others and my instance. This does not solve other problems which are keeping text2video from showing in tab or loading. There seems to be some interaction issues with Automatic1111. I hope they are solved soon so I can actually run this extention.

I checked and it seems to be working fine.
https://www.youtube.com/watch?v=6gbadk8lXus

**Comment by PonyWarrior** [comment]
Add tqdm==4.66.2 to requirements_versions.txt
