### ISSUE TITLE
[Bug]: It seems it cant create a folder

### ISSUE THREAD

**Issue by kolyan3445** [deforum-art/sd-webui-text2video#89]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

im trying to generate a text to video, it seems interpreter cant create a folder

### Steps to reproduce the problem

click a generate button

### WebUI and Deforum extension Commit IDs

webui commit id - [3715ece0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39)
txt2vid commit id - https://github.com/deforum-art/sd-webui-modelscope-text2video/commit/d16d9d47d63cf5ed87a4bf950dba1736b4b6f2c6

### What GPU were you using for launching?

NVIDIA RTX 2060 Super

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

![image](https://user-images.githubusercontent.com/55030059/229298500-eef9be22-397f-4709-860d-cc9ef2d68b41.png)
![image](https://user-images.githubusercontent.com/55030059/229298518-e60eb1f3-ca5d-42ec-88e9-d00a590b89ad.png)

### Console logs

```Shell
venv "C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 3715ece0adce7bf7c5e9c5ab3710b2fdc3848f39
Installing requirements for Web UI
Installing sd-dynamic-prompts requirements.txt

current transparent-background 1.2.3


Installing imageio-ffmpeg requirement for depthmap script
Installing pyqt5 requirement for depthmap script

Installing video2video requirement: sk-video

Launching Web UI with arguments: --xformers --no-half-vae
2023-04-01 17:56:25.0364228 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1641 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
Loading weights [fdffd3c312] from C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\models\Stable-diffusion\ambientmixAnAnime_v10.safetensors
Creating model from config: C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\models\VAE\orangemix.vae.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(2): badhandv4, easynegative
Model loaded in 98.5s (load weights from disk: 12.1s, load config: 0.1s, create model: 1.2s, apply weights to model: 63.5s, apply half(): 0.8s, load VAE: 1.3s, move model to device: 1.1s, load textual inversion embeddings: 18.4s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

Closing server running on port: 7860
Restarting UI...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ModelScope text2video extension for auto1111 webui
Git commit: Unknown
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
device cuda
Working in txt2vid mode
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]latents torch.Size([1, 4, 24, 24, 24]) tensor(0.0002, device='cuda:0') tensor(1.0018, device='cuda:0')
DDIM sampling tensor(1): 100%|█████████████████████████████████████████████████████████| 31/31 [00:50<00:00,  1.63s/it]
STARTING VAE ON GPU. 24 CHUNKS TO PROCESS██████████████████████████████████████████████| 31/31 [00:50<00:00,  1.37it/s]
VAE HALVED
DECODING FRAMES
VAE FINISHED
torch.Size([24, 3, 192, 192])
output/mp4s/20230401_191007514020.mp4
text2video finished, saving frames to C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\outputs/img2img-images\text2video-modelscope\20230401190401
Got a request to stitch frames to video using FFmpeg.
Frames:
C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\outputs/img2img-images\text2video-modelscope\20230401190401\%06d.png
To Video:
C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\outputs/img2img-images\text2video-modelscope\20230401190401\vid.mp4
Stitching *video*...
Stitching *video*...
Video stitching done in 4.14 seconds!
t2v complete, result saved at C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\outputs/img2img-images\text2video-modelscope\20230401190401
Traceback (most recent call last):
  File "C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 182, in process
    mp4 = open(outdir_current + os.path.sep + f"vid.mp4", 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kolya\\OneDrive\\Рабочий стол\\stablediff\\ai\\outputs/img2img-images\\text2video-modelscope\\20230401190401\\vid.mp4'
Exception occurred: [Errno 2] No such file or directory: 'C:\\Users\\kolya\\OneDrive\\Рабочий стол\\stablediff\\ai\\outputs/img2img-images\\text2video-modelscope\\20230401190401\\vid.mp4'
ModelScope text2video extension for auto1111 webui
Git commit: Unknown
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
device cuda
Working in txt2vid mode
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]latents torch.Size([1, 4, 24, 24, 24]) tensor(-0.0033, device='cuda:0') tensor(1.0038, device='cuda:0')
DDIM sampling tensor(1): 100%|█████████████████████████████████████████████████████████| 31/31 [00:34<00:00,  1.11s/it]
STARTING VAE ON GPU. 24 CHUNKS TO PROCESS██████████████████████████████████████████████| 31/31 [00:34<00:00,  1.38it/s]
VAE HALVED
DECODING FRAMES
VAE FINISHED
torch.Size([24, 3, 192, 192])
output/mp4s/20230401_191850411983.mp4
text2video finished, saving frames to C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\outputs/img2img-images\text2video-modelscope\20230401191135
Got a request to stitch frames to video using FFmpeg.
Frames:
C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\outputs/img2img-images\text2video-modelscope\20230401191135\%06d.png
To Video:
C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\outputs/img2img-images\text2video-modelscope\20230401191135\vid.mp4
Stitching *video*...
Stitching *video*...
Video stitching done in 31.17 seconds!
t2v complete, result saved at C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\outputs/img2img-images\text2video-modelscope\20230401191135
Traceback (most recent call last):
  File "C:\Users\kolya\OneDrive\Рабочий стол\stablediff\ai\extensions\sd-webui-modelscope-text2video\scripts\modelscope-text2vid.py", line 182, in process
    mp4 = open(outdir_current + os.path.sep + f"vid.mp4", 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kolya\\OneDrive\\Рабочий стол\\stablediff\\ai\\outputs/img2img-images\\text2video-modelscope\\20230401191135\\vid.mp4'
Exception occurred: [Errno 2] No such file or directory: 'C:\\Users\\kolya\\OneDrive\\Рабочий стол\\stablediff\\ai\\outputs/img2img-images\\text2video-modelscope\\20230401191135\\vid.mp4'
```

**Comment by kolyan3445** [comment]
additional note, this was right after the installing, i just restarted SD and it keeps doing this

**Comment by kabachuha** [comment]
Possibly, troubles with ffmpeg and Cyrillic names

Go to `C:\\Users\\kolya\\OneDrive\\Рабочий стол\\stablediff\\ai\\outputs/img2img-images\\text2video-modelscope\\20230401191135` and check if there are at least the images

**Comment by kolyan3445** [comment]
> Possibly, troubles with ffmpeg and Cyrillic names
> 
> Go to `C:\\Users\\kolya\\OneDrive\\Рабочий стол\\stablediff\\ai\\outputs/img2img-images\\text2video-modelscope\\20230401191135` and check if there are at least the images

Nah, nothing at all, not even a folder have been created

**Comment by kabachuha** [comment]
Got it, it's a OneDrive issue, it's known to cause errors for many projects, such as https://github.com/wesnoth/wesnoth

Move your stable-diffusion-webui folder elsewhere
